// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpAc7z-fZm-Dvt0eweV0Z2T-qBj0HEmQ',
    appId: '1:261904720154:web:ccdef23ea0c03e4e3f0ca3',
    messagingSenderId: '261904720154',
    projectId: 'test-d06ff',
    authDomain: 'test-d06ff.firebaseapp.com',
    storageBucket: 'test-d06ff.appspot.com',
    measurementId: 'G-VCJMD43JSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNszWCzN0oDduW4olekSc_kYAZZOGUws',
    appId: '1:261904720154:android:f9ed43853ded1ee13f0ca3',
    messagingSenderId: '261904720154',
    projectId: 'test-d06ff',
    storageBucket: 'test-d06ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSBhfABJmkEFhTZFAB44HFe2R1LcBgrA',
    appId: '1:261904720154:ios:a3e90f3e77b2da0e3f0ca3',
    messagingSenderId: '261904720154',
    projectId: 'test-d06ff',
    storageBucket: 'test-d06ff.appspot.com',
    iosBundleId: 'com.cds.beauty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSBhfABJmkEFhTZFAB44HFe2R1LcBgrA',
    appId: '1:261904720154:ios:a3e90f3e77b2da0e3f0ca3',
    messagingSenderId: '261904720154',
    projectId: 'test-d06ff',
    storageBucket: 'test-d06ff.appspot.com',
    iosBundleId: 'com.cds.beauty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRpAc7z-fZm-Dvt0eweV0Z2T-qBj0HEmQ',
    appId: '1:261904720154:web:cad1aba9a15134f43f0ca3',
    messagingSenderId: '261904720154',
    projectId: 'test-d06ff',
    authDomain: 'test-d06ff.firebaseapp.com',
    storageBucket: 'test-d06ff.appspot.com',
    measurementId: 'G-EFMXHQKVQ6',
  );
}
